apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mobileclient-admin
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mobile.k8s.io
    resources:
      - mobileclients
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
