apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mobileclient-users
rules:
  - apiGroups:
      - mobile.k8s.io
    resources:
      - mobileclients
    verbs:
      - get
      - list
      - watch
