apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mobileclient-users
rules:
  - apiGroups:
      - mdc.aerogear.org
    resources:
      - mobileclients
    verbs:
      - get
      - list
      - watch
