apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mobile-developer
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
    resourceNames:
      - mobile-developer-console
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mobile.k8s.io
    resources:
      - mobileclients
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - push.aerogear.org
    resources:
      - androidvariants
      - iosvariants
      - pushapplications
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mobile-security-service.aerogear.org
    resources:
      - mobilesecurityserviceapps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aerogear.org
    resources:
      - keycloakrealms
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - project.openshift.io
    resources:
      - projects
    resourceNames:
      - mobile-developer-console
    verbs:
      - get
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - list
      - get
