apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mobileclient-admin
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mobile.k8s.io
    resources:
      - mobileclients
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - push.aerogear.org
    resources:
      - androidvariants
      - iosvariants
      - pushapplications
      - unifiedpushservers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - metrics.aerogear.org
    resources:
      - appmetricsconfigs
      - appmetricsservices
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
