apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mobileclient-admin
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - mobile.k8s.io
    resources:
      - mobileclients
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - push.aerogear.org
    resources:
      - androidvariants
      - iosvariants
      - pushapplications
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - metrics.aerogear.org
    resources:
      - appmetricsconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - mobile-security-service.aerogear.org
    resources:
      - mobilesecurityserviceapps
    verbs:
      - get
      - list
      - watch
