apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-developer-console-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mobile-developer-console-operator
  template:
    metadata:
      labels:
        name: mobile-developer-console-operator
    spec:
      serviceAccountName: mobile-developer-console-operator
      containers:
        - name: mobile-developer-console-operator
          image: quay.io/aerogear/mobile-developer-console-operator:0.3.0
          command:
          - mobile-developer-console-operator
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 40m
              memory: 64Mi
            requests:
              cpu: 20m
              memory: 32Mi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mobile-developer-console-operator"
            - name: OPENSHIFT_HOST
              value: "${OPENSHIFT_HOST}"  # to be filled by whoever is deploying this file
            - name: UPS_DOCUMENTATION_URL
              value: https://docs.aerogear.org/limited-availability/downstream/ups.html
            - name: IDM_DOCUMENTATION_URL
              value: https://docs.aerogear.org/limited-availability/downstream/idm.html
            - name: SYNC_DOCUMENTATION_URL
              value: https://docs.aerogear.org/limited-availability/downstream/sync.html
            - name: MSS_DOCUMENTATION_URL
              value: https://docs.aerogear.org/limited-availability/downstream/mss.html
