apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: mobile-developer-console-operator
rules:
# The resources in this group are the CRs that the controllers in this
# operator react to. Nothing in the operator is expected to create or
# delete CRs, so those permissions are not given.
- apiGroups:
  - mdc.aerogear.org
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
  - update

# For "secondary resources", the operator needs to be able to do
# pretty much everything. The "deletecollection" permission is the
# only one not given here (if it needs to delete more than one
# instance of a kind, it can do them one-by-one).
- apiGroups:
  - ""
  resources:
  - events
  - services
  - services/finalizers
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

# These are needed to be able to run the operator itself
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - apps
  resourceNames:
  - mobile-developer-console-operator
  resources:
  - deployments/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - create
  - update
  - patch
  - delete

# Needed to be able to create ServiceMonitor for operator & operands
- apiGroups:
  - monitoring.coreos.com
  resources:
    - servicemonitors
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
