apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    monitoring-key: middleware
  name: mobile-developer-console
spec:
  endpoints:
    - path: /metrics
      port: web
  selector:
    matchLabels:
      internal: mdc